# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'manui.ui'
#
# Created: Wed Apr 27 10:40:38 2016
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui, QtWebKit

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class WebPage(QtWebKit.QWebPage):
    def javaScriptConsoleMessage(self, msg, line, source):
        print '%s line %d: %s' % (source, line, msg)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1254, 820)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.launchButton = QtGui.QPushButton(self.centralwidget)
        self.launchButton.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.launchButton.sizePolicy().hasHeightForWidth())
        self.launchButton.setSizePolicy(sizePolicy)
        self.launchButton.setObjectName(_fromUtf8("launchButton"))
        self.horizontalLayout_6.addWidget(self.launchButton)
        self.setHomeButton = QtGui.QPushButton(self.centralwidget)
        self.setHomeButton.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.setHomeButton.sizePolicy().hasHeightForWidth())
        self.setHomeButton.setSizePolicy(sizePolicy)
        self.setHomeButton.setObjectName(_fromUtf8("setHomeButton"))
        self.horizontalLayout_6.addWidget(self.setHomeButton)
        self.startWaypointListButton = QtGui.QPushButton(self.centralwidget)
        self.startWaypointListButton.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startWaypointListButton.sizePolicy().hasHeightForWidth())
        self.startWaypointListButton.setSizePolicy(sizePolicy)
        self.startWaypointListButton.setObjectName(_fromUtf8("startWaypointListButton"))
        self.horizontalLayout_6.addWidget(self.startWaypointListButton)
        self.comeHomeButton = QtGui.QPushButton(self.centralwidget)
        self.comeHomeButton.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comeHomeButton.sizePolicy().hasHeightForWidth())
        self.comeHomeButton.setSizePolicy(sizePolicy)
        self.comeHomeButton.setObjectName(_fromUtf8("comeHomeButton"))
        self.horizontalLayout_6.addWidget(self.comeHomeButton)
        self.landButton = QtGui.QPushButton(self.centralwidget)
        self.landButton.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.landButton.sizePolicy().hasHeightForWidth())
        self.landButton.setSizePolicy(sizePolicy)
        self.landButton.setObjectName(_fromUtf8("landButton"))
        self.horizontalLayout_6.addWidget(self.landButton)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.autonomousNavigationButton = QtGui.QPushButton(self.centralwidget)
        self.autonomousNavigationButton.setEnabled(False)
        self.autonomousNavigationButton.setObjectName(_fromUtf8("autonomousNavigationButton"))
        self.verticalLayout.addWidget(self.autonomousNavigationButton)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.webView = QtWebKit.QWebView(self.centralwidget)
        page = WebPage()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.webView.sizePolicy().hasHeightForWidth())
        self.webView.setSizePolicy(sizePolicy)
        self.webView.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.webView.setUrl(QtCore.QUrl(_fromUtf8("about:blank")))
        self.webView.setObjectName(_fromUtf8("webView"))
        self.horizontalLayout_2.addWidget(self.webView)
        self.line_3 = QtGui.QFrame(self.centralwidget)
        self.line_3.setFrameShape(QtGui.QFrame.VLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.horizontalLayout_2.addWidget(self.line_3)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.loadWaypointButton = QtGui.QPushButton(self.centralwidget)
        self.loadWaypointButton.setObjectName(_fromUtf8("loadWaypointButton"))
        self.gridLayout_2.addWidget(self.loadWaypointButton, 31, 0, 1, 1)
        self.gpsSatelitesText = QtGui.QLabel(self.centralwidget)
        self.gpsSatelitesText.setObjectName(_fromUtf8("gpsSatelitesText"))
        self.gridLayout_2.addWidget(self.gpsSatelitesText, 17, 1, 1, 1)
        self.label_23 = QtGui.QLabel(self.centralwidget)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.gridLayout_2.addWidget(self.label_23, 17, 0, 1, 1)
        self.waypointLongitudeText = QtGui.QLabel(self.centralwidget)
        self.waypointLongitudeText.setObjectName(_fromUtf8("waypointLongitudeText"))
        self.gridLayout_2.addWidget(self.waypointLongitudeText, 12, 1, 1, 1)
        self.line_6 = QtGui.QFrame(self.centralwidget)
        self.line_6.setFrameShape(QtGui.QFrame.HLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.gridLayout_2.addWidget(self.line_6, 23, 0, 1, 1)
        self.label_17 = QtGui.QLabel(self.centralwidget)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_2.addWidget(self.label_17, 21, 0, 1, 1)
        self.homeLongitudeText = QtGui.QLabel(self.centralwidget)
        self.homeLongitudeText.setObjectName(_fromUtf8("homeLongitudeText"))
        self.gridLayout_2.addWidget(self.homeLongitudeText, 25, 1, 1, 1)
        self.gpsHeadingText = QtGui.QLabel(self.centralwidget)
        self.gpsHeadingText.setObjectName(_fromUtf8("gpsHeadingText"))
        self.gridLayout_2.addWidget(self.gpsHeadingText, 22, 1, 1, 1)
        self.label_13 = QtGui.QLabel(self.centralwidget)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_2.addWidget(self.label_13, 18, 0, 1, 1)
        self.label_11 = QtGui.QLabel(self.centralwidget)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_2.addWidget(self.label_11, 10, 0, 1, 1)
        self.label_16 = QtGui.QLabel(self.centralwidget)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_2.addWidget(self.label_16, 15, 0, 1, 1)
        self.label_10 = QtGui.QLabel(self.centralwidget)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_2.addWidget(self.label_10, 6, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 30, 0, 1, 1)
        self.label_12 = QtGui.QLabel(self.centralwidget)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_2.addWidget(self.label_12, 7, 0, 1, 1)
        self.line_15 = QtGui.QFrame(self.centralwidget)
        self.line_15.setFrameShape(QtGui.QFrame.HLine)
        self.line_15.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_15.setObjectName(_fromUtf8("line_15"))
        self.gridLayout_2.addWidget(self.line_15, 3, 0, 1, 1)
        self.line_12 = QtGui.QFrame(self.centralwidget)
        self.line_12.setFrameShape(QtGui.QFrame.HLine)
        self.line_12.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_12.setObjectName(_fromUtf8("line_12"))
        self.gridLayout_2.addWidget(self.line_12, 9, 0, 1, 1)
        self.label_14 = QtGui.QLabel(self.centralwidget)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_2.addWidget(self.label_14, 19, 0, 1, 1)
        self.line_5 = QtGui.QFrame(self.centralwidget)
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.gridLayout_2.addWidget(self.line_5, 16, 0, 1, 1)
        self.batteryText = QtGui.QLabel(self.centralwidget)
        self.batteryText.setObjectName(_fromUtf8("batteryText"))
        self.gridLayout_2.addWidget(self.batteryText, 8, 1, 1, 1)
        self.label_15 = QtGui.QLabel(self.centralwidget)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_2.addWidget(self.label_15, 20, 0, 1, 1)
        self.gpsLongitudeText = QtGui.QLabel(self.centralwidget)
        self.gpsLongitudeText.setObjectName(_fromUtf8("gpsLongitudeText"))
        self.gridLayout_2.addWidget(self.gpsLongitudeText, 19, 1, 1, 1)
        self.gpsAltitudeText = QtGui.QLabel(self.centralwidget)
        self.gpsAltitudeText.setObjectName(_fromUtf8("gpsAltitudeText"))
        self.gridLayout_2.addWidget(self.gpsAltitudeText, 20, 1, 1, 1)
        self.gpsLatitudeText = QtGui.QLabel(self.centralwidget)
        self.gpsLatitudeText.setObjectName(_fromUtf8("gpsLatitudeText"))
        self.gridLayout_2.addWidget(self.gpsLatitudeText, 18, 1, 1, 1)
        self.line_8 = QtGui.QFrame(self.centralwidget)
        self.line_8.setFrameShape(QtGui.QFrame.HLine)
        self.line_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_8.setObjectName(_fromUtf8("line_8"))
        self.gridLayout_2.addWidget(self.line_8, 16, 1, 1, 1)
        self.line_9 = QtGui.QFrame(self.centralwidget)
        self.line_9.setFrameShape(QtGui.QFrame.HLine)
        self.line_9.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_9.setObjectName(_fromUtf8("line_9"))
        self.gridLayout_2.addWidget(self.line_9, 23, 1, 1, 1)
        self.label_28 = QtGui.QLabel(self.centralwidget)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.gridLayout_2.addWidget(self.label_28, 22, 0, 1, 1)
        self.label_35 = QtGui.QLabel(self.centralwidget)
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.gridLayout_2.addWidget(self.label_35, 25, 0, 1, 1)
        self.homeAltitudeText = QtGui.QLabel(self.centralwidget)
        self.homeAltitudeText.setObjectName(_fromUtf8("homeAltitudeText"))
        self.gridLayout_2.addWidget(self.homeAltitudeText, 26, 1, 1, 1)
        self.label_34 = QtGui.QLabel(self.centralwidget)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.gridLayout_2.addWidget(self.label_34, 24, 0, 1, 1)
        self.line_14 = QtGui.QFrame(self.centralwidget)
        self.line_14.setFrameShape(QtGui.QFrame.HLine)
        self.line_14.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_14.setObjectName(_fromUtf8("line_14"))
        self.gridLayout_2.addWidget(self.line_14, 9, 2, 1, 1)
        self.line_13 = QtGui.QFrame(self.centralwidget)
        self.line_13.setFrameShape(QtGui.QFrame.HLine)
        self.line_13.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_13.setObjectName(_fromUtf8("line_13"))
        self.gridLayout_2.addWidget(self.line_13, 9, 1, 1, 1)
        self.label_30 = QtGui.QLabel(self.centralwidget)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.gridLayout_2.addWidget(self.label_30, 11, 0, 1, 1)
        self.waypointIndexText = QtGui.QLabel(self.centralwidget)
        self.waypointIndexText.setObjectName(_fromUtf8("waypointIndexText"))
        self.gridLayout_2.addWidget(self.waypointIndexText, 10, 1, 1, 1)
        self.waypointLatitudeText = QtGui.QLabel(self.centralwidget)
        self.waypointLatitudeText.setObjectName(_fromUtf8("waypointLatitudeText"))
        self.gridLayout_2.addWidget(self.waypointLatitudeText, 11, 1, 1, 1)
        self.line_16 = QtGui.QFrame(self.centralwidget)
        self.line_16.setFrameShape(QtGui.QFrame.HLine)
        self.line_16.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_16.setObjectName(_fromUtf8("line_16"))
        self.gridLayout_2.addWidget(self.line_16, 3, 1, 1, 1)
        self.navigationStatusText = QtGui.QLabel(self.centralwidget)
        self.navigationStatusText.setObjectName(_fromUtf8("navigationStatusText"))
        self.gridLayout_2.addWidget(self.navigationStatusText, 7, 1, 1, 1)
        self.waypointDistanceText = QtGui.QLabel(self.centralwidget)
        self.waypointDistanceText.setObjectName(_fromUtf8("waypointDistanceText"))
        self.gridLayout_2.addWidget(self.waypointDistanceText, 15, 1, 1, 1)
        self.quadNameText = QtGui.QLabel(self.centralwidget)
        self.quadNameText.setObjectName(_fromUtf8("quadNameText"))
        self.gridLayout_2.addWidget(self.quadNameText, 6, 1, 1, 1)
        self.label_20 = QtGui.QLabel(self.centralwidget)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout_2.addWidget(self.label_20, 8, 0, 1, 1)
        self.label_21 = QtGui.QLabel(self.centralwidget)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout_2.addWidget(self.label_21, 14, 0, 1, 1)
        self.label_22 = QtGui.QLabel(self.centralwidget)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.gridLayout_2.addWidget(self.label_22, 13, 0, 1, 1)
        self.waypointHeightText = QtGui.QLabel(self.centralwidget)
        self.waypointHeightText.setObjectName(_fromUtf8("waypointHeightText"))
        self.gridLayout_2.addWidget(self.waypointHeightText, 13, 1, 1, 1)
        self.label_31 = QtGui.QLabel(self.centralwidget)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.gridLayout_2.addWidget(self.label_31, 12, 0, 1, 1)
        self.waypointVelocityText = QtGui.QLabel(self.centralwidget)
        self.waypointVelocityText.setObjectName(_fromUtf8("waypointVelocityText"))
        self.gridLayout_2.addWidget(self.waypointVelocityText, 14, 1, 1, 1)
        self.label_36 = QtGui.QLabel(self.centralwidget)
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.gridLayout_2.addWidget(self.label_36, 26, 0, 1, 1)
        self.gpsImuHeightText = QtGui.QLabel(self.centralwidget)
        self.gpsImuHeightText.setObjectName(_fromUtf8("gpsImuHeightText"))
        self.gridLayout_2.addWidget(self.gpsImuHeightText, 21, 1, 1, 1)
        self.label_18 = QtGui.QLabel(self.centralwidget)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_2.addWidget(self.label_18, 28, 0, 1, 1)
        self.homeLatitudeText = QtGui.QLabel(self.centralwidget)
        self.homeLatitudeText.setObjectName(_fromUtf8("homeLatitudeText"))
        self.gridLayout_2.addWidget(self.homeLatitudeText, 24, 1, 1, 1)
        self.managerStatusText = QtGui.QLabel(self.centralwidget)
        self.managerStatusText.setObjectName(_fromUtf8("managerStatusText"))
        self.gridLayout_2.addWidget(self.managerStatusText, 28, 1, 1, 1)
        self.line_7 = QtGui.QFrame(self.centralwidget)
        self.line_7.setFrameShape(QtGui.QFrame.HLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName(_fromUtf8("line_7"))
        self.gridLayout_2.addWidget(self.line_7, 27, 0, 1, 1)
        self.line_10 = QtGui.QFrame(self.centralwidget)
        self.line_10.setFrameShape(QtGui.QFrame.HLine)
        self.line_10.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_10.setObjectName(_fromUtf8("line_10"))
        self.gridLayout_2.addWidget(self.line_10, 27, 1, 1, 1)
        self.saveMapButton = QtGui.QPushButton(self.centralwidget)
        self.saveMapButton.setObjectName(_fromUtf8("saveMapButton"))
        self.gridLayout_2.addWidget(self.saveMapButton, 32, 0, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout_2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.line_2 = QtGui.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.verticalLayout.addWidget(self.line_2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.flightPathCheckbox = QtGui.QCheckBox(self.centralwidget)
        self.flightPathCheckbox.setChecked(True)
        self.flightPathCheckbox.setObjectName(_fromUtf8("flightPathCheckbox"))
        self.horizontalLayout.addWidget(self.flightPathCheckbox)
        self.waypointCheckbox = QtGui.QCheckBox(self.centralwidget)
        self.waypointCheckbox.setChecked(True)
        self.waypointCheckbox.setObjectName(_fromUtf8("waypointCheckbox"))
        self.horizontalLayout.addWidget(self.waypointCheckbox)
        self.quadrotorCheckbox = QtGui.QCheckBox(self.centralwidget)
        self.quadrotorCheckbox.setChecked(True)
        self.quadrotorCheckbox.setObjectName(_fromUtf8("quadrotorCheckbox"))
        self.horizontalLayout.addWidget(self.quadrotorCheckbox)
        self.trackQuadrotorCheckbox = QtGui.QCheckBox(self.centralwidget)
        self.trackQuadrotorCheckbox.setChecked(True)
        self.trackQuadrotorCheckbox.setObjectName(_fromUtf8("trackQuadrotorCheckbox"))
        self.horizontalLayout.addWidget(self.trackQuadrotorCheckbox)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.line_4 = QtGui.QFrame(self.centralwidget)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.verticalLayout.addWidget(self.line_4)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_4 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_4.addWidget(self.label_4)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.label_6 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_4.addWidget(self.label_6)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.label_5 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_4.addWidget(self.label_5)
        self.gridLayout.addLayout(self.horizontalLayout_4, 1, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 0, 2, 1, 1)
        self.velocitySlider = QtGui.QSlider(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.velocitySlider.sizePolicy().hasHeightForWidth())
        self.velocitySlider.setSizePolicy(sizePolicy)
        self.velocitySlider.setMaximum(100)
        self.velocitySlider.setSingleStep(10)
        self.velocitySlider.setOrientation(QtCore.Qt.Horizontal)
        self.velocitySlider.setTickPosition(QtGui.QSlider.TicksBelow)
        self.velocitySlider.setTickInterval(10)
        self.velocitySlider.setObjectName(_fromUtf8("velocitySlider"))
        self.gridLayout.addWidget(self.velocitySlider, 0, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_9 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_5.addWidget(self.label_9)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.label_8 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_5.addWidget(self.label_8)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4)
        self.label_7 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_5.addWidget(self.label_7)
        self.gridLayout.addLayout(self.horizontalLayout_5, 1, 3, 1, 1)
        self.heightSlider = QtGui.QSlider(self.centralwidget)
        self.heightSlider.setMaximum(30000)
        self.heightSlider.setSingleStep(1000)
        self.heightSlider.setPageStep(1000)
        self.heightSlider.setOrientation(QtCore.Qt.Horizontal)
        self.heightSlider.setTickPosition(QtGui.QSlider.TicksBelow)
        self.heightSlider.setTickInterval(1000)
        self.heightSlider.setObjectName(_fromUtf8("heightSlider"))
        self.gridLayout.addWidget(self.heightSlider, 0, 3, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout.addWidget(self.line)
        self.label = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout.addWidget(self.label)
        self.batteryBar = QtGui.QProgressBar(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.batteryBar.sizePolicy().hasHeightForWidth())
        self.batteryBar.setSizePolicy(sizePolicy)
        self.batteryBar.setProperty("value", 24)
        self.batteryBar.setObjectName(_fromUtf8("batteryBar"))
        self.verticalLayout.addWidget(self.batteryBar)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.launchButton.setText(QtGui.QApplication.translate("MainWindow", "Launch", None, QtGui.QApplication.UnicodeUTF8))
        self.setHomeButton.setText(QtGui.QApplication.translate("MainWindow", "Set Home", None, QtGui.QApplication.UnicodeUTF8))
        self.startWaypointListButton.setText(QtGui.QApplication.translate("MainWindow", "Start Waypoint List", None, QtGui.QApplication.UnicodeUTF8))
        self.comeHomeButton.setText(QtGui.QApplication.translate("MainWindow", "Come Home", None, QtGui.QApplication.UnicodeUTF8))
        self.landButton.setText(QtGui.QApplication.translate("MainWindow", "Land", None, QtGui.QApplication.UnicodeUTF8))
        self.autonomousNavigationButton.setText(QtGui.QApplication.translate("MainWindow", "Autonomous Navigation", None, QtGui.QApplication.UnicodeUTF8))
        self.loadWaypointButton.setText(QtGui.QApplication.translate("MainWindow", "Load Waypoint", None, QtGui.QApplication.UnicodeUTF8))
        self.gpsSatelitesText.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate("MainWindow", "Satelites: ", None, QtGui.QApplication.UnicodeUTF8))
        self.waypointLongitudeText.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("MainWindow", "Imu Height:", None, QtGui.QApplication.UnicodeUTF8))
        self.homeLongitudeText.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.gpsHeadingText.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("MainWindow", "Latitude: ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("MainWindow", "Waypoint List:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("MainWindow", "Distance: ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("MainWindow", "Navigation Status:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("MainWindow", "Longitude: ", None, QtGui.QApplication.UnicodeUTF8))
        self.batteryText.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("MainWindow", "Altitude: ", None, QtGui.QApplication.UnicodeUTF8))
        self.gpsLongitudeText.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.gpsAltitudeText.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.gpsLatitudeText.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_28.setText(QtGui.QApplication.translate("MainWindow", "Heading:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_35.setText(QtGui.QApplication.translate("MainWindow", "Home Longitude:", None, QtGui.QApplication.UnicodeUTF8))
        self.homeAltitudeText.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_34.setText(QtGui.QApplication.translate("MainWindow", "Home Latitude:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_30.setText(QtGui.QApplication.translate("MainWindow", "Latitude:", None, QtGui.QApplication.UnicodeUTF8))
        self.waypointIndexText.setText(QtGui.QApplication.translate("MainWindow", "0 of 0", None, QtGui.QApplication.UnicodeUTF8))
        self.waypointLatitudeText.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.navigationStatusText.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.waypointDistanceText.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.quadNameText.setText(QtGui.QApplication.translate("MainWindow", "name", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("MainWindow", "Battery: ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("MainWindow", "Velocity:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("MainWindow", "Height: ", None, QtGui.QApplication.UnicodeUTF8))
        self.waypointHeightText.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_31.setText(QtGui.QApplication.translate("MainWindow", "Longitude:", None, QtGui.QApplication.UnicodeUTF8))
        self.waypointVelocityText.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_36.setText(QtGui.QApplication.translate("MainWindow", "Home Altitude:", None, QtGui.QApplication.UnicodeUTF8))
        self.gpsImuHeightText.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("MainWindow", "Manager Status:", None, QtGui.QApplication.UnicodeUTF8))
        self.homeLatitudeText.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.managerStatusText.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.saveMapButton.setText(QtGui.QApplication.translate("MainWindow", "Save Plot Maps", None, QtGui.QApplication.UnicodeUTF8))
        self.flightPathCheckbox.setText(QtGui.QApplication.translate("MainWindow", "Show Flight Path", None, QtGui.QApplication.UnicodeUTF8))
        self.waypointCheckbox.setText(QtGui.QApplication.translate("MainWindow", "Show Waypoints", None, QtGui.QApplication.UnicodeUTF8))
        self.quadrotorCheckbox.setText(QtGui.QApplication.translate("MainWindow", "Show Quadrotor", None, QtGui.QApplication.UnicodeUTF8))
        self.trackQuadrotorCheckbox.setText(QtGui.QApplication.translate("MainWindow", "Track Quadrotor", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", " 0   ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "  50", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "100", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "  <html><head/><body><p><span style=\" font-weight:600;\">   Height:</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Velocity:</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", " 0          ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "15000", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "30000", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Battery:</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))

from PyQt4 import QtWebKit
