/* Auto-generated by genmsg_cpp for file /opt/ros/groovy/share/asctec_drivers/asctec_msgs/msg/CtrlInput.msg */
#ifndef ASCTEC_MSGS_MESSAGE_CTRLINPUT_H
#define ASCTEC_MSGS_MESSAGE_CTRLINPUT_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"

namespace asctec_msgs
{
template <class ContainerAllocator>
struct CtrlInput_ {
  typedef CtrlInput_<ContainerAllocator> Type;

  CtrlInput_()
  : header()
  , pitch(0)
  , roll(0)
  , yaw(0)
  , thrust(0)
  , ctrl(0)
  , chksum(0)
  {
  }

  CtrlInput_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , pitch(0)
  , roll(0)
  , yaw(0)
  , thrust(0)
  , ctrl(0)
  , chksum(0)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef int16_t _pitch_type;
  int16_t pitch;

  typedef int16_t _roll_type;
  int16_t roll;

  typedef int16_t _yaw_type;
  int16_t yaw;

  typedef int16_t _thrust_type;
  int16_t thrust;

  typedef int16_t _ctrl_type;
  int16_t ctrl;

  typedef int16_t _chksum_type;
  int16_t chksum;


  typedef boost::shared_ptr< ::asctec_msgs::CtrlInput_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::asctec_msgs::CtrlInput_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct CtrlInput
typedef  ::asctec_msgs::CtrlInput_<std::allocator<void> > CtrlInput;

typedef boost::shared_ptr< ::asctec_msgs::CtrlInput> CtrlInputPtr;
typedef boost::shared_ptr< ::asctec_msgs::CtrlInput const> CtrlInputConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::asctec_msgs::CtrlInput_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::asctec_msgs::CtrlInput_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace asctec_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::asctec_msgs::CtrlInput_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::asctec_msgs::CtrlInput_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::asctec_msgs::CtrlInput_<ContainerAllocator> > {
  static const char* value() 
  {
    return "6a2f3591afa7529005dcc3a5acd6e490";
  }

  static const char* value(const  ::asctec_msgs::CtrlInput_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x6a2f3591afa75290ULL;
  static const uint64_t static_value2 = 0x05dcc3a5acd6e490ULL;
};

template<class ContainerAllocator>
struct DataType< ::asctec_msgs::CtrlInput_<ContainerAllocator> > {
  static const char* value() 
  {
    return "asctec_msgs/CtrlInput";
  }

  static const char* value(const  ::asctec_msgs::CtrlInput_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::asctec_msgs::CtrlInput_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# Software License Agreement (BSD License)\n\
#\n\
# Copyright (c) 2010\n\
#  William Morris <morris@ee.ccny.cuny.edu>\n\
#  Ivan Dryanovski <ivan.dryanovski@gmail.com>\n\
# All rights reserved.\n\
#\n\
# Redistribution and use in source and binary forms, with or without\n\
# modification, are permitted provided that the following conditions\n\
# are met:\n\
#\n\
#  * Redistributions of source code must retain the above copyright\n\
#    notice, this list of conditions and the following disclaimer.\n\
#  * Redistributions in binary form must reproduce the above\n\
#    copyright notice, this list of conditions and the following\n\
#    disclaimer in the documentation and/or other materials provided\n\
#    with the distribution.\n\
#  * Neither the name of CCNY Robotics Lab nor the names of its\n\
#    contributors may be used to endorse or promote products derived\n\
#    from this software without specific prior written permission.\n\
#\n\
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS\n\
# \"AS IS\" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT\n\
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS\n\
# FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE\n\
# COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,\n\
# INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,\n\
# BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;\n\
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER\n\
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT\n\
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN\n\
# ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE\n\
# POSSIBILITY OF SUCH DAMAGE.\n\
\n\
Header header\n\
# serial command (=Scientific Interface)\n\
# Pitch input: -2047 .. 2047 (0 = neutral)\n\
int16 pitch\n\
# Roll input: -2047 .. 2047 (0 = neutral)\n\
int16 roll\n\
# R/C Stick input: -2047 .. 2047 (0 = neutral)\n\
int16 yaw\n\
# Collective: 0 .. 4095 (= 0 .. 100%)\n\
int16 thrust\n\
# control byte:\n\
#    bit 0: pitch control enabled\n\
#    bit 1: roll control enabled\n\
#    bit 2: yaw control enabled\n\
#    bit 3: thrust control enabled\n\
#  These bits can be used to only enable one axis at a time and thus to control\n\
#  the other axes manually. This usually helps a lot to set up and finetune\n\
#  controllers for each axis seperately.\n\
int16 ctrl\n\
int16 chksum\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::asctec_msgs::CtrlInput_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::asctec_msgs::CtrlInput_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::asctec_msgs::CtrlInput_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::asctec_msgs::CtrlInput_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.pitch);
    stream.next(m.roll);
    stream.next(m.yaw);
    stream.next(m.thrust);
    stream.next(m.ctrl);
    stream.next(m.chksum);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct CtrlInput_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::asctec_msgs::CtrlInput_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::asctec_msgs::CtrlInput_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "pitch: ";
    Printer<int16_t>::stream(s, indent + "  ", v.pitch);
    s << indent << "roll: ";
    Printer<int16_t>::stream(s, indent + "  ", v.roll);
    s << indent << "yaw: ";
    Printer<int16_t>::stream(s, indent + "  ", v.yaw);
    s << indent << "thrust: ";
    Printer<int16_t>::stream(s, indent + "  ", v.thrust);
    s << indent << "ctrl: ";
    Printer<int16_t>::stream(s, indent + "  ", v.ctrl);
    s << indent << "chksum: ";
    Printer<int16_t>::stream(s, indent + "  ", v.chksum);
  }
};


} // namespace message_operations
} // namespace ros

#endif // ASCTEC_MSGS_MESSAGE_CTRLINPUT_H

