/* Auto-generated by genmsg_cpp for file /opt/ros/groovy/share/asctec_drivers/asctec_msgs/msg/GPSData.msg */
#ifndef ASCTEC_MSGS_MESSAGE_GPSDATA_H
#define ASCTEC_MSGS_MESSAGE_GPSDATA_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"

namespace asctec_msgs
{
template <class ContainerAllocator>
struct GPSData_ {
  typedef GPSData_<ContainerAllocator> Type;

  GPSData_()
  : header()
  , latitude(0)
  , longitude(0)
  , height(0)
  , speed_x(0)
  , speed_y(0)
  , heading(0)
  , horizontal_accuracy(0)
  , vertical_accuracy(0)
  , speed_accuracy(0)
  , numSV(0)
  , status(0)
  {
  }

  GPSData_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , latitude(0)
  , longitude(0)
  , height(0)
  , speed_x(0)
  , speed_y(0)
  , heading(0)
  , horizontal_accuracy(0)
  , vertical_accuracy(0)
  , speed_accuracy(0)
  , numSV(0)
  , status(0)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef int32_t _latitude_type;
  int32_t latitude;

  typedef int32_t _longitude_type;
  int32_t longitude;

  typedef int32_t _height_type;
  int32_t height;

  typedef int32_t _speed_x_type;
  int32_t speed_x;

  typedef int32_t _speed_y_type;
  int32_t speed_y;

  typedef int32_t _heading_type;
  int32_t heading;

  typedef int32_t _horizontal_accuracy_type;
  int32_t horizontal_accuracy;

  typedef int32_t _vertical_accuracy_type;
  int32_t vertical_accuracy;

  typedef int32_t _speed_accuracy_type;
  int32_t speed_accuracy;

  typedef int32_t _numSV_type;
  int32_t numSV;

  typedef int32_t _status_type;
  int32_t status;


  typedef boost::shared_ptr< ::asctec_msgs::GPSData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::asctec_msgs::GPSData_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct GPSData
typedef  ::asctec_msgs::GPSData_<std::allocator<void> > GPSData;

typedef boost::shared_ptr< ::asctec_msgs::GPSData> GPSDataPtr;
typedef boost::shared_ptr< ::asctec_msgs::GPSData const> GPSDataConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::asctec_msgs::GPSData_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::asctec_msgs::GPSData_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace asctec_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::asctec_msgs::GPSData_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::asctec_msgs::GPSData_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::asctec_msgs::GPSData_<ContainerAllocator> > {
  static const char* value() 
  {
    return "b71de9435ba6759a86f427d436c58ccb";
  }

  static const char* value(const  ::asctec_msgs::GPSData_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xb71de9435ba6759aULL;
  static const uint64_t static_value2 = 0x86f427d436c58ccbULL;
};

template<class ContainerAllocator>
struct DataType< ::asctec_msgs::GPSData_<ContainerAllocator> > {
  static const char* value() 
  {
    return "asctec_msgs/GPSData";
  }

  static const char* value(const  ::asctec_msgs::GPSData_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::asctec_msgs::GPSData_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# Software License Agreement (BSD License)\n\
#\n\
# Copyright (c) 2010\n\
#  William Morris <morris@ee.ccny.cuny.edu>\n\
#  Ivan Dryanovski <ivan.dryanovski@gmail.com>\n\
# All rights reserved.\n\
#\n\
# Redistribution and use in source and binary forms, with or without\n\
# modification, are permitted provided that the following conditions\n\
# are met:\n\
#\n\
#  * Redistributions of source code must retain the above copyright\n\
#    notice, this list of conditions and the following disclaimer.\n\
#  * Redistributions in binary form must reproduce the above\n\
#    copyright notice, this list of conditions and the following\n\
#    disclaimer in the documentation and/or other materials provided\n\
#    with the distribution.\n\
#  * Neither the name of CCNY Robotics Lab nor the names of its\n\
#    contributors may be used to endorse or promote products derived\n\
#    from this software without specific prior written permission.\n\
#\n\
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS\n\
# \"AS IS\" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT\n\
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS\n\
# FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE\n\
# COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,\n\
# INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,\n\
# BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;\n\
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER\n\
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT\n\
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN\n\
# ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE\n\
# POSSIBILITY OF SUCH DAMAGE.\n\
\n\
Header header\n\
# latitude/longitude in deg * 10^7\n\
int32 latitude\n\
int32 longitude\n\
\n\
#GPS height in mm\n\
int32 height\n\
\n\
#speed in x (E/W) and y(N/S) in mm/s\n\
int32 speed_x\n\
int32 speed_y\n\
\n\
#GPS heading in deg * 100\n\
int32 heading\n\
\n\
#accuracy estimates in mm and mm/s\n\
int32 horizontal_accuracy\n\
int32 vertical_accuracy\n\
int32 speed_accuracy\n\
\n\
#number of satellite vehicles used in NAV solution\n\
int32 numSV\n\
\n\
#GPS status information; 0x03 = valid GPS fix\n\
int32 status\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::asctec_msgs::GPSData_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::asctec_msgs::GPSData_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::asctec_msgs::GPSData_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::asctec_msgs::GPSData_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.latitude);
    stream.next(m.longitude);
    stream.next(m.height);
    stream.next(m.speed_x);
    stream.next(m.speed_y);
    stream.next(m.heading);
    stream.next(m.horizontal_accuracy);
    stream.next(m.vertical_accuracy);
    stream.next(m.speed_accuracy);
    stream.next(m.numSV);
    stream.next(m.status);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct GPSData_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::asctec_msgs::GPSData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::asctec_msgs::GPSData_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "latitude: ";
    Printer<int32_t>::stream(s, indent + "  ", v.latitude);
    s << indent << "longitude: ";
    Printer<int32_t>::stream(s, indent + "  ", v.longitude);
    s << indent << "height: ";
    Printer<int32_t>::stream(s, indent + "  ", v.height);
    s << indent << "speed_x: ";
    Printer<int32_t>::stream(s, indent + "  ", v.speed_x);
    s << indent << "speed_y: ";
    Printer<int32_t>::stream(s, indent + "  ", v.speed_y);
    s << indent << "heading: ";
    Printer<int32_t>::stream(s, indent + "  ", v.heading);
    s << indent << "horizontal_accuracy: ";
    Printer<int32_t>::stream(s, indent + "  ", v.horizontal_accuracy);
    s << indent << "vertical_accuracy: ";
    Printer<int32_t>::stream(s, indent + "  ", v.vertical_accuracy);
    s << indent << "speed_accuracy: ";
    Printer<int32_t>::stream(s, indent + "  ", v.speed_accuracy);
    s << indent << "numSV: ";
    Printer<int32_t>::stream(s, indent + "  ", v.numSV);
    s << indent << "status: ";
    Printer<int32_t>::stream(s, indent + "  ", v.status);
  }
};


} // namespace message_operations
} // namespace ros

#endif // ASCTEC_MSGS_MESSAGE_GPSDATA_H

