/* Auto-generated by genmsg_cpp for file /opt/ros/groovy/share/asctec_drivers/asctec_msgs/msg/IMURawData.msg */
#ifndef ASCTEC_MSGS_MESSAGE_IMURAWDATA_H
#define ASCTEC_MSGS_MESSAGE_IMURAWDATA_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"

namespace asctec_msgs
{
template <class ContainerAllocator>
struct IMURawData_ {
  typedef IMURawData_<ContainerAllocator> Type;

  IMURawData_()
  : header()
  , pressure(0)
  , gyro_x(0)
  , gyro_y(0)
  , gyro_z(0)
  , mag_x(0)
  , mag_y(0)
  , mag_z(0)
  , acc_x(0)
  , acc_y(0)
  , acc_z(0)
  , temp_gyro(0)
  , temp_ADC(0)
  {
  }

  IMURawData_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , pressure(0)
  , gyro_x(0)
  , gyro_y(0)
  , gyro_z(0)
  , mag_x(0)
  , mag_y(0)
  , mag_z(0)
  , acc_x(0)
  , acc_y(0)
  , acc_z(0)
  , temp_gyro(0)
  , temp_ADC(0)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef int32_t _pressure_type;
  int32_t pressure;

  typedef int16_t _gyro_x_type;
  int16_t gyro_x;

  typedef int16_t _gyro_y_type;
  int16_t gyro_y;

  typedef int16_t _gyro_z_type;
  int16_t gyro_z;

  typedef int16_t _mag_x_type;
  int16_t mag_x;

  typedef int16_t _mag_y_type;
  int16_t mag_y;

  typedef int16_t _mag_z_type;
  int16_t mag_z;

  typedef int16_t _acc_x_type;
  int16_t acc_x;

  typedef int16_t _acc_y_type;
  int16_t acc_y;

  typedef int16_t _acc_z_type;
  int16_t acc_z;

  typedef int16_t _temp_gyro_type;
  int16_t temp_gyro;

  typedef int32_t _temp_ADC_type;
  int32_t temp_ADC;


  typedef boost::shared_ptr< ::asctec_msgs::IMURawData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::asctec_msgs::IMURawData_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct IMURawData
typedef  ::asctec_msgs::IMURawData_<std::allocator<void> > IMURawData;

typedef boost::shared_ptr< ::asctec_msgs::IMURawData> IMURawDataPtr;
typedef boost::shared_ptr< ::asctec_msgs::IMURawData const> IMURawDataConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::asctec_msgs::IMURawData_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::asctec_msgs::IMURawData_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace asctec_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::asctec_msgs::IMURawData_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::asctec_msgs::IMURawData_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::asctec_msgs::IMURawData_<ContainerAllocator> > {
  static const char* value() 
  {
    return "2cfd4b9ba0bc72be7f937c948d990cd9";
  }

  static const char* value(const  ::asctec_msgs::IMURawData_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x2cfd4b9ba0bc72beULL;
  static const uint64_t static_value2 = 0x7f937c948d990cd9ULL;
};

template<class ContainerAllocator>
struct DataType< ::asctec_msgs::IMURawData_<ContainerAllocator> > {
  static const char* value() 
  {
    return "asctec_msgs/IMURawData";
  }

  static const char* value(const  ::asctec_msgs::IMURawData_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::asctec_msgs::IMURawData_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# Software License Agreement (BSD License)\n\
#\n\
# Copyright (c) 2010\n\
#  William Morris <morris@ee.ccny.cuny.edu>\n\
#  Ivan Dryanovski <ivan.dryanovski@gmail.com>\n\
# All rights reserved.\n\
#\n\
# Redistribution and use in source and binary forms, with or without\n\
# modification, are permitted provided that the following conditions\n\
# are met:\n\
#\n\
#  * Redistributions of source code must retain the above copyright\n\
#    notice, this list of conditions and the following disclaimer.\n\
#  * Redistributions in binary form must reproduce the above\n\
#    copyright notice, this list of conditions and the following\n\
#    disclaimer in the documentation and/or other materials provided\n\
#    with the distribution.\n\
#  * Neither the name of CCNY Robotics Lab nor the names of its\n\
#    contributors may be used to endorse or promote products derived\n\
#    from this software without specific prior written permission.\n\
#\n\
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS\n\
# \"AS IS\" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT\n\
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS\n\
# FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE\n\
# COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,\n\
# INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,\n\
# BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;\n\
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER\n\
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT\n\
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN\n\
# ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE\n\
# POSSIBILITY OF SUCH DAMAGE.\n\
\n\
Header header\n\
#pressure sensor 24-bit value, not scaled but bias free\n\
int32 pressure\n\
\n\
#16-bit gyro readings; 32768 = 2.5V\n\
int16 gyro_x\n\
int16 gyro_y\n\
int16 gyro_z\n\
\n\
#10-bit magnetic field sensor readings\n\
int16 mag_x\n\
int16 mag_y\n\
int16 mag_z\n\
\n\
#16-bit accelerometer readings\n\
int16 acc_x\n\
int16 acc_y\n\
int16 acc_z\n\
\n\
#16-bit temperature measurement using yaw-gyro internal sensor\n\
int16 temp_gyro\n\
\n\
#16-bit temperature measurement using ADC internal sensor\n\
int32 temp_ADC\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::asctec_msgs::IMURawData_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::asctec_msgs::IMURawData_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::asctec_msgs::IMURawData_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::asctec_msgs::IMURawData_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.pressure);
    stream.next(m.gyro_x);
    stream.next(m.gyro_y);
    stream.next(m.gyro_z);
    stream.next(m.mag_x);
    stream.next(m.mag_y);
    stream.next(m.mag_z);
    stream.next(m.acc_x);
    stream.next(m.acc_y);
    stream.next(m.acc_z);
    stream.next(m.temp_gyro);
    stream.next(m.temp_ADC);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct IMURawData_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::asctec_msgs::IMURawData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::asctec_msgs::IMURawData_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "pressure: ";
    Printer<int32_t>::stream(s, indent + "  ", v.pressure);
    s << indent << "gyro_x: ";
    Printer<int16_t>::stream(s, indent + "  ", v.gyro_x);
    s << indent << "gyro_y: ";
    Printer<int16_t>::stream(s, indent + "  ", v.gyro_y);
    s << indent << "gyro_z: ";
    Printer<int16_t>::stream(s, indent + "  ", v.gyro_z);
    s << indent << "mag_x: ";
    Printer<int16_t>::stream(s, indent + "  ", v.mag_x);
    s << indent << "mag_y: ";
    Printer<int16_t>::stream(s, indent + "  ", v.mag_y);
    s << indent << "mag_z: ";
    Printer<int16_t>::stream(s, indent + "  ", v.mag_z);
    s << indent << "acc_x: ";
    Printer<int16_t>::stream(s, indent + "  ", v.acc_x);
    s << indent << "acc_y: ";
    Printer<int16_t>::stream(s, indent + "  ", v.acc_y);
    s << indent << "acc_z: ";
    Printer<int16_t>::stream(s, indent + "  ", v.acc_z);
    s << indent << "temp_gyro: ";
    Printer<int16_t>::stream(s, indent + "  ", v.temp_gyro);
    s << indent << "temp_ADC: ";
    Printer<int32_t>::stream(s, indent + "  ", v.temp_ADC);
  }
};


} // namespace message_operations
} // namespace ros

#endif // ASCTEC_MSGS_MESSAGE_IMURAWDATA_H

