/* Auto-generated by genmsg_cpp for file /opt/ros/groovy/share/asctec_drivers/asctec_msgs/msg/RCData.msg */
#ifndef ASCTEC_MSGS_MESSAGE_RCDATA_H
#define ASCTEC_MSGS_MESSAGE_RCDATA_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"

namespace asctec_msgs
{
template <class ContainerAllocator>
struct RCData_ {
  typedef RCData_<ContainerAllocator> Type;

  RCData_()
  : header()
  , channels_in()
  , channels_out()
  , lock(0)
  {
    channels_in.assign(0);
    channels_out.assign(0);
  }

  RCData_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , channels_in()
  , channels_out()
  , lock(0)
  {
    channels_in.assign(0);
    channels_out.assign(0);
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef boost::array<int16_t, 8>  _channels_in_type;
  boost::array<int16_t, 8>  channels_in;

  typedef boost::array<int16_t, 8>  _channels_out_type;
  boost::array<int16_t, 8>  channels_out;

  typedef int16_t _lock_type;
  int16_t lock;


  typedef boost::shared_ptr< ::asctec_msgs::RCData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::asctec_msgs::RCData_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct RCData
typedef  ::asctec_msgs::RCData_<std::allocator<void> > RCData;

typedef boost::shared_ptr< ::asctec_msgs::RCData> RCDataPtr;
typedef boost::shared_ptr< ::asctec_msgs::RCData const> RCDataConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::asctec_msgs::RCData_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::asctec_msgs::RCData_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace asctec_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::asctec_msgs::RCData_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::asctec_msgs::RCData_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::asctec_msgs::RCData_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d486363e6033911606202acafb1bc1a0";
  }

  static const char* value(const  ::asctec_msgs::RCData_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xd486363e60339116ULL;
  static const uint64_t static_value2 = 0x06202acafb1bc1a0ULL;
};

template<class ContainerAllocator>
struct DataType< ::asctec_msgs::RCData_<ContainerAllocator> > {
  static const char* value() 
  {
    return "asctec_msgs/RCData";
  }

  static const char* value(const  ::asctec_msgs::RCData_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::asctec_msgs::RCData_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# Software License Agreement (BSD License)\n\
#\n\
# Copyright (c) 2010\n\
#  William Morris <morris@ee.ccny.cuny.edu>\n\
#  Ivan Dryanovski <ivan.dryanovski@gmail.com>\n\
# All rights reserved.\n\
#\n\
# Redistribution and use in source and binary forms, with or without\n\
# modification, are permitted provided that the following conditions\n\
# are met:\n\
#\n\
#  * Redistributions of source code must retain the above copyright\n\
#    notice, this list of conditions and the following disclaimer.\n\
#  * Redistributions in binary form must reproduce the above\n\
#    copyright notice, this list of conditions and the following\n\
#    disclaimer in the documentation and/or other materials provided\n\
#    with the distribution.\n\
#  * Neither the name of CCNY Robotics Lab nor the names of its\n\
#    contributors may be used to endorse or promote products derived\n\
#    from this software without specific prior written permission.\n\
#\n\
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS\n\
# \"AS IS\" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT\n\
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS\n\
# FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE\n\
# COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,\n\
# INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,\n\
# BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;\n\
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER\n\
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT\n\
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN\n\
# ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE\n\
# POSSIBILITY OF SUCH DAMAGE.\n\
\n\
#    struct RC_DATA\n\
#    {\n\
#      //channels as read from R/C receiver\n\
#      unsigned short channels_in[8];\n\
#      //channels bias free, remapped and scaled to 0..4095\n\
#      unsigned short channels_out[8];\n\
#     //Indicator for valid R/C receiption\n\
#      unsigned char lock;\n\
#    };\n\
Header header\n\
# channels as read from R/C receiver\n\
int16[8] channels_in\n\
\n\
#channels bias free, remapped and scaled to 0..4095\n\
int16[8] channels_out\n\
\n\
#indicator for valid R/C receiption\n\
int16 lock\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::asctec_msgs::RCData_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::asctec_msgs::RCData_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::asctec_msgs::RCData_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::asctec_msgs::RCData_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.channels_in);
    stream.next(m.channels_out);
    stream.next(m.lock);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct RCData_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::asctec_msgs::RCData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::asctec_msgs::RCData_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "channels_in[]" << std::endl;
    for (size_t i = 0; i < v.channels_in.size(); ++i)
    {
      s << indent << "  channels_in[" << i << "]: ";
      Printer<int16_t>::stream(s, indent + "  ", v.channels_in[i]);
    }
    s << indent << "channels_out[]" << std::endl;
    for (size_t i = 0; i < v.channels_out.size(); ++i)
    {
      s << indent << "  channels_out[" << i << "]: ";
      Printer<int16_t>::stream(s, indent + "  ", v.channels_out[i]);
    }
    s << indent << "lock: ";
    Printer<int16_t>::stream(s, indent + "  ", v.lock);
  }
};


} // namespace message_operations
} // namespace ros

#endif // ASCTEC_MSGS_MESSAGE_RCDATA_H

