/* Auto-generated by genmsg_cpp for file /opt/ros/groovy/share/asctec_drivers/asctec_msgs/msg/WaypointCommand.msg */
#ifndef ASCTEC_MSGS_MESSAGE_WAYPOINTCOMMAND_H
#define ASCTEC_MSGS_MESSAGE_WAYPOINTCOMMAND_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"

namespace asctec_msgs
{
template <class ContainerAllocator>
struct WaypointCommand_ {
  typedef WaypointCommand_<ContainerAllocator> Type;

  WaypointCommand_()
  : header()
  , cmd()
  {
  }

  WaypointCommand_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , cmd(_alloc)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _cmd_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  cmd;


  typedef boost::shared_ptr< ::asctec_msgs::WaypointCommand_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::asctec_msgs::WaypointCommand_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct WaypointCommand
typedef  ::asctec_msgs::WaypointCommand_<std::allocator<void> > WaypointCommand;

typedef boost::shared_ptr< ::asctec_msgs::WaypointCommand> WaypointCommandPtr;
typedef boost::shared_ptr< ::asctec_msgs::WaypointCommand const> WaypointCommandConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::asctec_msgs::WaypointCommand_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::asctec_msgs::WaypointCommand_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace asctec_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::asctec_msgs::WaypointCommand_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::asctec_msgs::WaypointCommand_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::asctec_msgs::WaypointCommand_<ContainerAllocator> > {
  static const char* value() 
  {
    return "4276af4fed90fb499f3ed97a1942bbe3";
  }

  static const char* value(const  ::asctec_msgs::WaypointCommand_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x4276af4fed90fb49ULL;
  static const uint64_t static_value2 = 0x9f3ed97a1942bbe3ULL;
};

template<class ContainerAllocator>
struct DataType< ::asctec_msgs::WaypointCommand_<ContainerAllocator> > {
  static const char* value() 
  {
    return "asctec_msgs/WaypointCommand";
  }

  static const char* value(const  ::asctec_msgs::WaypointCommand_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::asctec_msgs::WaypointCommand_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
string cmd\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::asctec_msgs::WaypointCommand_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::asctec_msgs::WaypointCommand_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::asctec_msgs::WaypointCommand_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::asctec_msgs::WaypointCommand_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.cmd);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct WaypointCommand_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::asctec_msgs::WaypointCommand_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::asctec_msgs::WaypointCommand_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "cmd: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.cmd);
  }
};


} // namespace message_operations
} // namespace ros

#endif // ASCTEC_MSGS_MESSAGE_WAYPOINTCOMMAND_H

