(cl:defpackage asctec_msgs-msg
  (:use )
  (:export
   "<IMURAWDATA>"
   "IMURAWDATA"
   "<CURRENTWAY>"
   "CURRENTWAY"
   "<WAYPOINTDATA>"
   "WAYPOINTDATA"
   "<RCDATA>"
   "RCDATA"
   "<CONTROLLEROUTPUT>"
   "CONTROLLEROUTPUT"
   "<LLSTATUS>"
   "LLSTATUS"
   "<GPSDATA>"
   "GPSDATA"
   "<GPSDATAADVANCED>"
   "GPSDATAADVANCED"
   "<IMUCALCDATA>"
   "IMUCALCDATA"
   "<WAYPOINTCOMMAND>"
   "WAYPOINTCOMMAND"
   "<CTRLINPUT>"
   "CTRLINPUT"
  ))

