(cl:in-package asctec_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          ANGLE_NICK-VAL
          ANGLE_NICK
          ANGLE_ROLL-VAL
          ANGLE_ROLL
          ANGLE_YAW-VAL
          ANGLE_YAW
          ANGVEL_NICK-VAL
          ANGVEL_NICK
          ANGVEL_ROLL-VAL
          ANGVEL_ROLL
          ANGVEL_YAW-VAL
          ANGVEL_YAW
          ACC_X_CALIB-VAL
          ACC_X_CALIB
          ACC_Y_CALIB-VAL
          ACC_Y_CALIB
          ACC_Z_CALIB-VAL
          ACC_Z_CALIB
          ACC_X-VAL
          ACC_X
          ACC_Y-VAL
          ACC_Y
          ACC_Z-VAL
          ACC_Z
          ACC_ANGLE_NICK-VAL
          ACC_ANGLE_NICK
          ACC_ANGLE_ROLL-VAL
          ACC_ANGLE_ROLL
          ACC_ABSOLUTE_VALUE-VAL
          ACC_ABSOLUTE_VALUE
          HX-VAL
          HX
          HY-VAL
          HY
          HZ-VAL
          HZ
          MAG_HEADING-VAL
          MAG_HEADING
          SPEED_X-VAL
          SPEED_X
          SPEED_Y-VAL
          SPEED_Y
          SPEED_Z-VAL
          SPEED_Z
          HEIGHT-VAL
          HEIGHT
          DHEIGHT-VAL
          DHEIGHT
          DHEIGHT_REFERENCE-VAL
          DHEIGHT_REFERENCE
          HEIGHT_REFERENCE-VAL
          HEIGHT_REFERENCE
))