(cl:in-package asctec_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          LATITUDE-VAL
          LATITUDE
          LONGITUDE-VAL
          LONGITUDE
          HEIGHT-VAL
          HEIGHT
          SPEED_X-VAL
          SPEED_X
          SPEED_Y-VAL
          SPEED_Y
          HEADING-VAL
          HEADING
          HORIZONTAL_ACCURACY-VAL
          HORIZONTAL_ACCURACY
          VERTICAL_ACCURACY-VAL
          VERTICAL_ACCURACY
          SPEED_ACCURACY-VAL
          SPEED_ACCURACY
          NUMSV-VAL
          NUMSV
          STATUS-VAL
          STATUS
          LATITUDE_BEST_ESTIMATE-VAL
          LATITUDE_BEST_ESTIMATE
          LONGITUDE_BEST_ESTIMATE-VAL
          LONGITUDE_BEST_ESTIMATE
          SPEED_X_BEST_ESTIMATE-VAL
          SPEED_X_BEST_ESTIMATE
          SPEED_Y_BEST_ESTIMATE-VAL
          SPEED_Y_BEST_ESTIMATE
))